import Link from 'next/link'
import './globals.css'
import { Control } from './Control'
//import { useEffect, useState } from 'react'

export const metadata = {
  title: 'Web tutorial',
  description: 'Generated by pixuihong!',
}

export default async function RootLayout({ children }) {

  //revalidate 를 사용한 캐시 미적용
  const cacheOption = { next : { revalidate : 0 }}

  //no-store를 이용한 캐쉬 미적용
  // const cacheOption = { cache : 'no-store'}

  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', cacheOption);
  const topics = await resp.json();

  //client 컴포넌트 에서 사용되는 기능들
  /*
  const [topics, setTopics] = useState([]);
  useEffect(()=>{
    fetch('http://localhost:9999/topics')
    .then((res)=>{
        return res.json();
    }).then((result)=>{
        console.log('result : ', result);
        setTopics(result);
    });
  },[])*/
  return (
    <html>
      <body>
      <h1><Link href="/"></Link>WEB</h1>
      <ol>
        {topics.map((topic)=>{
          return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
        })}
      </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
